"""Runtime records for the mobile field API.

Three things the phone writes have no home in the existing stores:

* **agent-task handling state** — the incident pipeline already produces real
  agent tasks (``backend/simulation/persistence.py``), but a *field technician*
  acknowledging and completing one is a separate lifecycle that must survive a
  restart. That overlay lives here; the task itself is never copied, so the
  list can never drift from the engine's record.
* **reported issues** — a field report is a new record with an owner and a
  severity. Nothing else in the backend stores one.
* **notifications** — an in-app feed generated by real events (an issue was
  reported, an approval was decided). It is written when the event happens, not
  synthesised on read.

One SQLite file (``P117_MOBILE_DB``, default ``data/mobile.db``). The
simulation database is opened **read-only**: listing tasks must never be able
to mutate the engine's state, and a missing or unreadable engine database
degrades to an empty list rather than an error — an honest "no tasks" beats a
fabricated one.
"""

from __future__ import annotations

import json
import logging
import os
import secrets
import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

#: The field-handling lifecycle. ``PENDING`` is the state of an imported task
#: that no technician has touched yet; the terminal states are terminal.
AGENT_TASK_STATUSES = ("PENDING", "ACKNOWLEDGED", "IN_PROGRESS", "COMPLETED", "FAILED")
_TERMINAL_TASK_STATUSES = frozenset({"COMPLETED", "FAILED"})

_SCHEMA = """
CREATE TABLE IF NOT EXISTS agent_task_state (
    task_id         TEXT PRIMARY KEY,
    status          TEXT NOT NULL,
    acknowledged_at TEXT,
    acknowledged_by TEXT,
    completed_at    TEXT,
    completed_by    TEXT,
    notes           TEXT,
    evidence        TEXT NOT NULL DEFAULT '[]',
    updated_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS issues (
    id             TEXT PRIMARY KEY,
    equipment_id   TEXT NOT NULL,
    equipment_name TEXT,
    description    TEXT NOT NULL,
    severity       TEXT NOT NULL,
    reported_by    TEXT NOT NULL,
    reported_at    TEXT NOT NULL,
    evidence       TEXT NOT NULL DEFAULT '[]',
    work_order_id  TEXT
);

CREATE TABLE IF NOT EXISTS notifications (
    id             TEXT PRIMARY KEY,
    user           TEXT NOT NULL,
    type           TEXT NOT NULL,
    title          TEXT NOT NULL,
    body           TEXT NOT NULL,
    timestamp      TEXT NOT NULL,
    is_read        INTEGER NOT NULL DEFAULT 0,
    reference_id   TEXT,
    reference_type TEXT
);

CREATE INDEX IF NOT EXISTS ix_notifications_user ON notifications(user, timestamp);

CREATE TABLE IF NOT EXISTS evidence_uploads (
    document_id   TEXT PRIMARY KEY,
    equipment_id  TEXT,
    work_order_id TEXT,
    caption       TEXT,
    uploaded_by   TEXT,
    uploaded_at   TEXT NOT NULL
);
"""


class MobileStateError(ValueError):
    """A requested mobile-state transition is not allowed."""

    reason = "invalid_transition"
    status_code = 409


def default_mobile_db() -> Path:
    """``P117_MOBILE_DB`` if set, else ``<repo>/data/mobile.db``."""
    override = os.getenv("P117_MOBILE_DB", "").strip()
    if override:
        return Path(override).expanduser()
    return Path(__file__).resolve().parents[2] / "data" / "mobile.db"


def default_simulation_db() -> Path:
    """``P117_SIMULATION_DB`` if set, else ``<repo>/data/simulation.db``.

    Mirrors ``backend.simulation.persistence.DEFAULT_DB``. It is duplicated
    rather than imported so this module's read-only connection cannot be
    affected by the engine's own store initialisation (which seeds plants).
    """
    override = os.getenv("P117_SIMULATION_DB", "").strip()
    if override:
        return Path(override).expanduser()
    return Path(__file__).resolve().parents[2] / "data" / "simulation.db"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


class MobileStore:
    """SQLite-backed field state, plus a read-only view of the engine's tasks."""

    def __init__(
        self,
        db_path: str | Path | None = None,
        *,
        simulation_db: str | Path | None = None,
    ) -> None:
        self._db_path = Path(db_path) if db_path else default_mobile_db()
        if str(self._db_path) != ":memory:":
            self._db_path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.RLock()
        self._db = sqlite3.connect(str(self._db_path), check_same_thread=False)
        self._db.row_factory = sqlite3.Row
        with self._lock:
            self._db.executescript(_SCHEMA)
            self._db.commit()
        self._simulation_db = Path(simulation_db) if simulation_db else default_simulation_db()

    @property
    def path(self) -> Path:
        return self._db_path

    def close(self) -> None:
        with self._lock:
            self._db.close()

    # ------------------------------------------------------- agent tasks
    def _simulation_rows(self, sql: str, params: tuple = ()) -> list[dict[str, Any]]:
        """Query the engine's task table read-only; degrade to ``[]``.

        The engine owns this file and writes to it while the API serves
        requests. A read-only connection (URI ``mode=ro``) is used so a bug in
        a GET can never write to it, and any failure is reported as "no tasks"
        rather than turned into a 500 or an invented record.
        """
        path = self._simulation_db
        if not path.exists():
            return []
        try:
            connection = sqlite3.connect(f"file:{path}?mode=ro", uri=True, check_same_thread=False)
        except sqlite3.Error as exc:  # pragma: no cover - permissions/OS dependent
            logger.warning("simulation store unavailable for agent tasks: %s", exc)
            return []
        try:
            connection.row_factory = sqlite3.Row
            return [dict(row) for row in connection.execute(sql, params).fetchall()]
        except sqlite3.Error as exc:
            # A fresh checkout that has never run the simulation has no
            # agent_tasks table. That is an empty task list, not an error.
            logger.debug("agent task query failed: %s", exc)
            return []
        finally:
            connection.close()

    _TASK_SELECT = (
        "SELECT t.id, t.incident_id, t.agent, t.title, t.status AS agent_status,"
        " t.result, t.wall_ts, t.sequence, i.severity, i.origin_equipment,"
        " (SELECT COUNT(*) FROM agent_evidence e WHERE e.task_id = t.id) AS evidence_count"
        " FROM agent_tasks t LEFT JOIN incidents i ON i.id = t.incident_id"
    )

    def _overlay(self, task_id: str) -> dict[str, Any] | None:
        with self._lock:
            row = self._db.execute(
                "SELECT * FROM agent_task_state WHERE task_id=?", (str(task_id),)
            ).fetchone()
        return dict(row) if row is not None else None

    def _overlays(self, task_ids: list[str]) -> dict[str, dict[str, Any]]:
        if not task_ids:
            return {}
        placeholders = ",".join("?" for _ in task_ids)
        with self._lock:
            rows = self._db.execute(
                f"SELECT * FROM agent_task_state WHERE task_id IN ({placeholders})",
                tuple(task_ids),
            ).fetchall()
        return {str(row["task_id"]): dict(row) for row in rows}

    @staticmethod
    def _merge_task(row: dict[str, Any], overlay: dict[str, Any] | None) -> dict[str, Any]:
        merged = dict(row)
        merged["field_status"] = (overlay or {}).get("status") or "PENDING"
        merged["acknowledged_at"] = (overlay or {}).get("acknowledged_at")
        merged["acknowledged_by"] = (overlay or {}).get("acknowledged_by")
        merged["completed_at"] = (overlay or {}).get("completed_at")
        merged["completed_by"] = (overlay or {}).get("completed_by")
        merged["field_notes"] = (overlay or {}).get("notes")
        try:
            merged["field_evidence"] = json.loads((overlay or {}).get("evidence") or "[]")
        except ValueError:
            merged["field_evidence"] = []
        return merged

    def list_agent_tasks(self, *, limit: int = 200, offset: int = 0) -> list[dict[str, Any]]:
        rows = self._simulation_rows(
            self._TASK_SELECT + " ORDER BY t.wall_ts DESC, t.sequence ASC LIMIT ? OFFSET ?",
            (max(1, min(int(limit), 500)), max(0, int(offset))),
        )
        overlays = self._overlays([str(row["id"]) for row in rows])
        return [self._merge_task(row, overlays.get(str(row["id"]))) for row in rows]

    def agent_task(self, task_id: str) -> dict[str, Any]:
        rows = self._simulation_rows(
            self._TASK_SELECT + " WHERE lower(t.id)=lower(?)", (str(task_id),)
        )
        if not rows:
            raise KeyError(task_id)
        return self._merge_task(rows[0], self._overlay(str(rows[0]["id"])))

    def _write_overlay(self, task_id: str, **patch: Any) -> None:
        current = self._overlay(task_id) or {}
        current.update(patch)
        current["task_id"] = task_id
        current["updated_at"] = _now()
        with self._lock:
            self._db.execute(
                "INSERT INTO agent_task_state (task_id,status,acknowledged_at,acknowledged_by,"
                "completed_at,completed_by,notes,evidence,updated_at)"
                " VALUES (:task_id,:status,:acknowledged_at,:acknowledged_by,:completed_at,"
                ":completed_by,:notes,:evidence,:updated_at)"
                " ON CONFLICT(task_id) DO UPDATE SET status=excluded.status,"
                " acknowledged_at=excluded.acknowledged_at, acknowledged_by=excluded.acknowledged_by,"
                " completed_at=excluded.completed_at, completed_by=excluded.completed_by,"
                " notes=excluded.notes, evidence=excluded.evidence, updated_at=excluded.updated_at",
                {
                    "task_id": task_id,
                    "status": current.get("status") or "PENDING",
                    "acknowledged_at": current.get("acknowledged_at"),
                    "acknowledged_by": current.get("acknowledged_by"),
                    "completed_at": current.get("completed_at"),
                    "completed_by": current.get("completed_by"),
                    "notes": current.get("notes"),
                    "evidence": current.get("evidence") or "[]",
                    "updated_at": current["updated_at"],
                },
            )
            self._db.commit()

    def acknowledge_agent_task(self, task_id: str, *, actor: str) -> dict[str, Any]:
        task = self.agent_task(task_id)  # 404 for an unknown task
        current = str(task.get("field_status") or "PENDING")
        if current in _TERMINAL_TASK_STATUSES:
            raise MobileStateError(f"{task_id}: already {current}; it cannot be acknowledged")
        # Acknowledging a task already in progress must not walk it backwards.
        status = "IN_PROGRESS" if current == "IN_PROGRESS" else "ACKNOWLEDGED"
        self._write_overlay(
            str(task["id"]),
            status=status,
            acknowledged_at=_now(),
            acknowledged_by=actor,
        )
        return self.agent_task(task_id)

    def complete_agent_task(
        self,
        task_id: str,
        *,
        actor: str,
        notes: str | None = None,
        evidence_ids: list[str] | None = None,
    ) -> dict[str, Any]:
        self.agent_task(task_id)  # 404 for an unknown task
        self._write_overlay(
            task_id,
            status="COMPLETED",
            completed_at=_now(),
            completed_by=actor,
            notes=notes,
            evidence=json.dumps(list(evidence_ids or [])),
        )
        return self.agent_task(task_id)

    # ------------------------------------------------------------- issues
    def create_issue(
        self,
        *,
        equipment_id: str,
        equipment_name: str | None,
        description: str,
        severity: str,
        reported_by: str,
        evidence_ids: list[str] | None = None,
        work_order_id: str | None = None,
    ) -> dict[str, Any]:
        issue_id = f"ISSUE-{secrets.token_hex(4).upper()}"
        row = {
            "id": issue_id,
            "equipment_id": equipment_id,
            "equipment_name": equipment_name,
            "description": description,
            "severity": severity.upper(),
            "reported_by": reported_by,
            "reported_at": _now(),
            "evidence": list(evidence_ids or []),
            "work_order_id": work_order_id,
        }
        with self._lock:
            self._db.execute(
                "INSERT INTO issues (id,equipment_id,equipment_name,description,severity,"
                "reported_by,reported_at,evidence,work_order_id) VALUES (?,?,?,?,?,?,?,?,?)",
                (
                    row["id"],
                    row["equipment_id"],
                    row["equipment_name"],
                    row["description"],
                    row["severity"],
                    row["reported_by"],
                    row["reported_at"],
                    json.dumps(row["evidence"]),
                    row["work_order_id"],
                ),
            )
            self._db.commit()
        return row

    def issue(self, issue_id: str) -> dict[str, Any]:
        with self._lock:
            row = self._db.execute("SELECT * FROM issues WHERE id=?", (str(issue_id),)).fetchone()
        if row is None:
            raise KeyError(issue_id)
        return self._issue_row(row)

    @staticmethod
    def _issue_row(row: sqlite3.Row) -> dict[str, Any]:
        data = dict(row)
        try:
            data["evidence"] = json.loads(data.get("evidence") or "[]")
        except ValueError:
            data["evidence"] = []
        return data

    # ------------------------------------------------------ notifications
    def add_notification(
        self,
        *,
        user: str,
        notification_type: str,
        title: str,
        body: str,
        reference_id: str | None = None,
        reference_type: str | None = None,
    ) -> dict[str, Any]:
        notification_id = f"NOTIF-{secrets.token_hex(4).upper()}"
        timestamp = _now()
        with self._lock:
            self._db.execute(
                "INSERT INTO notifications (id,user,type,title,body,timestamp,is_read,"
                "reference_id,reference_type) VALUES (?,?,?,?,?,?,0,?,?)",
                (
                    notification_id,
                    user,
                    notification_type,
                    title,
                    body,
                    timestamp,
                    reference_id,
                    reference_type,
                ),
            )
            self._db.commit()
        return {
            "id": notification_id,
            "user": user,
            "type": notification_type,
            "title": title,
            "body": body,
            "timestamp": timestamp,
            "is_read": False,
            "reference_id": reference_id,
            "reference_type": reference_type,
        }

    def notifications(self, *, user: str, limit: int = 100) -> list[dict[str, Any]]:
        with self._lock:
            rows = self._db.execute(
                "SELECT * FROM notifications WHERE user=? ORDER BY timestamp DESC, id DESC LIMIT ?",
                (str(user), max(1, min(int(limit), 500))),
            ).fetchall()
        return [dict(row) for row in rows]

    def mark_notification_read(self, notification_id: str, *, user: str) -> bool:
        with self._lock:
            cursor = self._db.execute(
                "UPDATE notifications SET is_read=1 WHERE id=? AND user=?",
                (str(notification_id), str(user)),
            )
            self._db.commit()
        return bool(cursor.rowcount)

    # ---------------------------------------------------------- evidence
    def record_evidence_upload(
        self,
        *,
        document_id: str,
        equipment_id: str | None,
        work_order_id: str | None,
        caption: str | None,
        uploaded_by: str,
    ) -> None:
        """Persist the field context the multipart upload carried.

        ``DocumentStorage`` stores the bytes and a filename; the equipment and
        work-order links are metadata the field client sends and would otherwise
        be dropped on the floor.
        """
        with self._lock:
            self._db.execute(
                "INSERT OR REPLACE INTO evidence_uploads (document_id,equipment_id,work_order_id,"
                "caption,uploaded_by,uploaded_at) VALUES (?,?,?,?,?,?)",
                (document_id, equipment_id, work_order_id, caption, uploaded_by, _now()),
            )
            self._db.commit()


__all__ = [
    "AGENT_TASK_STATUSES",
    "MobileStateError",
    "MobileStore",
    "default_mobile_db",
    "default_simulation_db",
]
