"use client";

/** ArtifactCard + ArtifactPreview — deliverables with visible provenance. */
import { useState } from "react";
import { Modal } from "@/components/ui/overlays";
import { Button, Tag, timeAgo } from "@/components/ui/primitives";
import { Icon } from "@/components/ui/Icon";
import type { ArtifactRecord } from "@/types";

export function ArtifactCard({ artifact }: { artifact: ArtifactRecord }) {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button className="cs-artifact" onClick={() => setOpen(true)} aria-label={`Preview ${artifact.filename}`}>
        <span className="cs-artifact__icon">{artifact.kind.toUpperCase()}</span>
        <span style={{ minWidth: 0 }}>
          <div className="cs-mono" style={{ fontSize: 12, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
            {artifact.filename}
          </div>
          <div className="cs-row__sub">
            {timeAgo(artifact.created_at)} · sha256 {artifact.sha256}
          </div>
        </span>
        <span style={{ marginLeft: "auto" }}>
          {artifact.verified ? <Tag tone="ok">Verified ✓</Tag> : <Tag tone="warn">Pending</Tag>}
        </span>
      </button>
      {open && <ArtifactPreview artifact={artifact} onClose={() => setOpen(false)} />}
    </>
  );
}

export function ArtifactPreview({ artifact, onClose }: { artifact: ArtifactRecord; onClose: () => void }) {
  return (
    <Modal title={artifact.filename} wide onClose={onClose}>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 240px", gap: 18 }}>
        <div
          className="cs-scan"
          style={{
            border: "1px solid var(--line)",
            borderRadius: 8,
            background: "var(--bg-1)",
            minHeight: 380,
            padding: 28,
          }}
        >
          <p className="cs-mono cs-text-cyan" style={{ marginTop: 0, fontSize: 10, letterSpacing: "0.3em" }}>
            PREVIEW — {artifact.kind.toUpperCase()}
          </p>
          <h3 style={{ margin: "6px 0 10px", fontSize: 17, letterSpacing: "-0.01em" }}>
            {artifact.filename.replace(/\.(pdf|pptx|docx|xlsx)$/, "").replace(/_/g, " ")}
          </h3>
          <p style={{ color: "var(--ink-2)", fontSize: 13, lineHeight: 1.7 }}>
            Generated by the Maintenance Agent from job {artifact.job_id ?? "—"}. The full
            document is available via export; this surface renders structure and provenance,
            not a byte-faithful page render.
          </p>
          <div style={{ display: "flex", flexDirection: "column", gap: 8, marginTop: 18 }}>
            {["Summary", "Evidence base", "Analysis", "Recommendation", "Verification record"].map((s, i) => (
              <div
                key={s}
                style={{
                  display: "flex",
                  gap: 9,
                  alignItems: "center",
                  fontSize: 12.5,
                  color: "var(--ink-2)",
                  animation: `p117-fade-up 480ms var(--ease-out) ${i * 90}ms both`,
                }}
              >
                <Icon name="doc" size={13} /> {s}
                <span style={{ flex: 1, borderBottom: "1px dashed var(--line)" }} />
                <span className="cs-mono cs-text-ok" style={{ fontSize: 10 }}>✓</span>
              </div>
            ))}
          </div>
        </div>

        <aside style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          <div className="cs-panel cs-panel--hud">
            <div className="cs-panel__body" style={{ display: "flex", flexDirection: "column", gap: 9, fontSize: 12.5 }}>
              <p
                className="cs-mono cs-dim"
                style={{ margin: 0, fontSize: 9.5, letterSpacing: "0.3em", textTransform: "uppercase" }}
              >
                Provenance
              </p>
              <span>
                Generated from <b>3 sources</b>
              </span>
              <span>
                Verified against <b>3 sources</b>
              </span>
              <span className="cs-mono cs-dim" style={{ fontSize: 10 }}>
                sha256 {artifact.sha256}
              </span>
              <span className="cs-mono cs-dim" style={{ fontSize: 10 }}>
                job {artifact.job_id ?? "—"}
              </span>
              <span>{artifact.verified ? <Tag tone="ok">Verified ✓</Tag> : <Tag tone="warn">Unverified</Tag>}</span>
            </div>
          </div>
          <Button variant="primary">
            <Icon name="download" size={14} /> Export
          </Button>
          <Button onClick={onClose}>Close</Button>
        </aside>
      </div>
    </Modal>
  );
}
