import { defaultSensors, FM_BY_KIND, assemblePlant } from "./custom";
import type { EquipmentDef, PlantDef } from "./types";

export interface PlantTemplate {
  id: string;
  name: string;
  description: string;
  equipment: EquipmentDef[];
  connections: PlantDef["connections"];
}

function node(kind: EquipmentDef["kind"], tag: string, name: string, x: number, y: number, criticality = 2): EquipmentDef {
  const id = `e-${tag}`;
  const sensorTag = tag.replace(/^[A-Z]+-/, "");
  return {
    id,
    tag,
    name,
    kind,
    area_id: "custom",
    x,
    y,
    criticality,
    capacity: 100,
    state: "normal",
    sensors: defaultSensors(kind, id, sensorTag),
    failure_modes: FM_BY_KIND[kind],
    manufacturer: "Project 117 Synthetic Plant",
    model: "SIM-2026",
    installed: "2026-09-11",
    last_inspection: "2026-09-11",
  };
}

function pipes(ids: string[]): PlantDef["connections"] {
  return ids.slice(0, -1).map((source, i) => ({
    id: `pl-template-${i + 1}`,
    kind: "pipe",
    source,
    target: ids[i + 1],
    medium: "process",
    capacity: 100,
    flow: 82,
    status: "normal",
    leaking: false,
    enabled: true,
  }));
}

const REFINERY_EQUIPMENT = [
  node("tank", "T-101", "Crude Storage Tank", 130, 240, 2),
  node("pump", "P-101", "Crude Charge Pump A/B", 130, 480, 1),
  node("vessel", "D-101", "Desalter Unit", 360, 240, 1),
  node("furnace", "F-101", "Crude Furnace", 360, 480, 1),
  node("column", "C-101", "Atmospheric Distillation", 590, 200, 1),
  node("column", "C-102", "Vacuum Distillation", 590, 480, 1),
  node("column", "C-201", "FCC Unit", 820, 200, 1),
  node("vessel", "H-201", "Hydrocracker Reactor", 820, 480, 1),
  node("vessel", "A-301", "Amine Treating Unit", 1050, 160, 1),
  node("safety", "FLARE-01", "Flare Stack & ESD", 1050, 320, 1),
  node("vessel", "S-301", "SRU Sulfur Recovery", 1050, 480, 1),
  node("vessel", "H-301", "Hydrotreater", 1050, 640, 1),
  node("utility", "CT-401", "Cooling Tower", 1280, 160, 2),
  node("furnace", "B-401", "Boiler Package", 1280, 320, 2),
  node("motor", "PG-401", "Power Generator", 1280, 480, 2),
  node("tank", "T-501", "LPG Storage Tank", 1510, 160, 2),
  node("tank", "T-502", "Gasoline Storage Tank", 1510, 320, 2),
  node("tank", "T-503", "Diesel Storage Tank", 1510, 480, 2),
  node("tank", "T-504", "Jet Fuel Storage Tank", 1510, 640, 2),
];

const STEEL_EQUIPMENT = [
  node("conveyor", "CV-210", "Raw Material Feed", 130, 510, 2),
  node("furnace", "F-220", "Coke / Sinter Heat", 350, 390, 1),
  node("furnace", "BF-230", "Blast Furnace", 590, 390, 1),
  node("vessel", "HM-240", "Hot Metal Ladle", 820, 390, 1),
  node("furnace", "BOF-250", "Basic Oxygen Furnace", 1060, 510, 1),
  node("pump", "P-255", "Cooling Water Pumps", 820, 690, 1),
  node("motor", "M-260", "Caster Drive Motors", 1290, 510, 1),
  node("conveyor", "CC-270", "Continuous Casting", 1520, 510, 1),
  node("motor", "RM-280", "Rolling Mill Stand", 1750, 510, 1),
];

export const BUILDER_TEMPLATES: PlantTemplate[] = [
  {
    id: "template-refinery",
    name: "Oil Refinery",
    description: "Crude receipt through desalter, distillation, hydrotreating, reforming, blending and storage.",
    equipment: REFINERY_EQUIPMENT,
    connections: pipes(REFINERY_EQUIPMENT.map((e) => e.id)),
  },
  {
    id: "template-steel",
    name: "Iron & Steel Plant",
    description: "Raw material feed through sinter/coke, blast furnace, hot metal handling, BOF, casting and rolling.",
    equipment: STEEL_EQUIPMENT,
    connections: [
      ...pipes(STEEL_EQUIPMENT.filter((e) => e.tag !== "P-255").map((e) => e.id)),
      {
        id: "pl-template-cooling",
        kind: "pipe",
        source: "e-P-255",
        target: "e-CC-270",
        medium: "utility",
        capacity: 100,
        flow: 76,
        status: "normal",
        leaking: false,
        enabled: true,
      },
    ],
  },
  {
    id: "template-transfer",
    name: "Transfer Train",
    description: "Storage tank feeding a duty pump with control valve regulation into a destination vessel.",
    equipment: [
      {
        id: "e-TK-9001",
        tag: "TK-9001",
        name: "Feed Surge Tank",
        kind: "tank",
        area_id: "custom",
        x: 240,
        y: 460,
        criticality: 2,
        capacity: 100,
        state: "normal",
        sensors: defaultSensors("tank", "e-TK-9001", "9001"),
        failure_modes: FM_BY_KIND["tank"],
        manufacturer: "Custom Industries",
        model: "TK-STD-500",
        installed: "2026-09-11",
        last_inspection: "2026-09-11",
      },
      {
        id: "e-P-9002",
        tag: "P-9002",
        name: "Feed Charge Pump",
        kind: "pump",
        area_id: "custom",
        x: 640,
        y: 460,
        criticality: 1,
        capacity: 120,
        state: "normal",
        sensors: defaultSensors("pump", "e-P-9002", "9002"),
        failure_modes: FM_BY_KIND["pump"],
        manufacturer: "FlowServe",
        model: "MARK-3",
        installed: "2026-09-11",
        last_inspection: "2026-09-11",
      },
      {
        id: "e-V-9003",
        tag: "V-9003",
        name: "Flow Control Valve",
        kind: "valve",
        area_id: "custom",
        x: 1020,
        y: 460,
        criticality: 2,
        capacity: 100,
        state: "normal",
        sensors: defaultSensors("valve", "e-V-9003", "9003"),
        failure_modes: FM_BY_KIND["valve"],
        manufacturer: "Fisher",
        model: "ET-200",
        installed: "2026-09-11",
        last_inspection: "2026-09-11",
      },
      {
        id: "e-VS-9004",
        tag: "VS-9004",
        name: "Flash Separator Vessel",
        kind: "vessel",
        area_id: "custom",
        x: 1400,
        y: 460,
        criticality: 1,
        capacity: 80,
        state: "normal",
        sensors: defaultSensors("vessel", "e-VS-9004", "9004"),
        failure_modes: FM_BY_KIND["vessel"],
        manufacturer: "CBI Vessels",
        model: "HP-HORIZ-40",
        installed: "2026-09-11",
        last_inspection: "2026-09-11",
      },
    ],
    connections: [
      {
        id: "pl-c1",
        kind: "pipe",
        source: "e-TK-9001",
        target: "e-P-9002",
        medium: "process",
        capacity: 100,
        flow: 85,
        status: "normal",
        leaking: false,
        enabled: true,
      },
      {
        id: "pl-c2",
        kind: "pipe",
        source: "e-P-9002",
        target: "e-V-9003",
        medium: "process",
        capacity: 100,
        flow: 85,
        status: "normal",
        leaking: false,
        enabled: true,
      },
      {
        id: "pl-c3",
        kind: "pipe",
        source: "e-V-9003",
        target: "e-VS-9004",
        medium: "process",
        capacity: 100,
        flow: 85,
        status: "normal",
        leaking: false,
        enabled: true,
      },
    ],
  },
  {
    id: "template-compression",
    name: "Gas Compression & Cooling",
    description: "Feed separator into multi-stage gas compressor, shell-and-tube cooler, and knock-out vessel.",
    equipment: [
      {
        id: "e-VS-9010",
        tag: "VS-9010",
        name: "Suction Scrubber",
        kind: "vessel",
        area_id: "custom",
        x: 280,
        y: 460,
        criticality: 2,
        capacity: 90,
        state: "normal",
        sensors: defaultSensors("vessel", "e-VS-9010", "9010"),
        failure_modes: FM_BY_KIND["vessel"],
        manufacturer: "Process Fabricators",
        model: "SCRUB-10",
        installed: "2026-09-11",
        last_inspection: "2026-09-11",
      },
      {
        id: "e-C-9011",
        tag: "C-9011",
        name: "Centrifugal Gas Compressor",
        kind: "compressor",
        area_id: "custom",
        x: 680,
        y: 460,
        criticality: 1,
        capacity: 250,
        state: "normal",
        sensors: defaultSensors("compressor", "e-C-9011", "9011"),
        failure_modes: FM_BY_KIND["compressor"],
        manufacturer: "Siemens Energy",
        model: "STC-SV",
        installed: "2026-09-11",
        last_inspection: "2026-09-11",
      },
      {
        id: "e-E-9012",
        tag: "E-9012",
        name: "Discharge Gas Cooler",
        kind: "exchanger",
        area_id: "custom",
        x: 1080,
        y: 460,
        criticality: 2,
        capacity: 140,
        state: "normal",
        sensors: defaultSensors("exchanger", "e-E-9012", "9012"),
        failure_modes: FM_BY_KIND["exchanger"],
        manufacturer: "Alfa Laval",
        model: "Compabloc",
        installed: "2026-09-11",
        last_inspection: "2026-09-11",
      },
      {
        id: "e-ESD-9013",
        tag: "ESD-9013",
        name: "Gas Detection & ESD Station",
        kind: "safety",
        area_id: "custom",
        x: 1440,
        y: 460,
        criticality: 1,
        capacity: 1,
        state: "normal",
        sensors: defaultSensors("safety", "e-ESD-9013", "9013"),
        failure_modes: FM_BY_KIND["safety"],
        manufacturer: "Dräger",
        model: "Polytron 8000",
        installed: "2026-09-11",
        last_inspection: "2026-09-11",
      },
    ],
    connections: [
      {
        id: "pl-c11",
        kind: "pipe",
        source: "e-VS-9010",
        target: "e-C-9011",
        medium: "process",
        capacity: 200,
        flow: 180,
        status: "normal",
        leaking: false,
        enabled: true,
      },
      {
        id: "pl-c12",
        kind: "pipe",
        source: "e-C-9011",
        target: "e-E-9012",
        medium: "process",
        capacity: 200,
        flow: 180,
        status: "normal",
        leaking: false,
        enabled: true,
      },
      {
        id: "pl-c13",
        kind: "pipe",
        source: "e-E-9012",
        target: "e-ESD-9013",
        medium: "process",
        capacity: 200,
        flow: 180,
        status: "normal",
        leaking: false,
        enabled: true,
      },
    ],
  },
];
