"""Coherent synthetic demo data for the materials domain.

WHAT THIS IS
------------
Generated demo content, so a fresh deployment has something real to show. Every
record it writes carries ``data_status = SYNTHETIC_DEMO`` and a note saying so.
None of it is MRPL data, no supplier is a real company, and no price is a market
quote. The UI is required to display that status, and the API returns it on every
payload, so a figure from here can never be mistaken for a measurement.

WHAT MAKES IT *COHERENT* rather than a pile of rows
---------------------------------------------------
Every foreign key resolves, and it resolves against the **real** plant:

* ``equipment_id`` values are real Project 117 plant asset ids from
  ``backend.simulation.datasets.load_plant("refinery")`` — ``e-P-1001`` is the
  crude charge pump from the live dataset. No asset code is invented, so an
  equipment→spare recommendation lands on a machine the simulation actually runs.
* ``failure_mode`` values are the dataset's own modes (``seal_leak``,
  ``bearing_wear``, ``cavitation`` …), so the maintenance requirement can be
  matched to a diagnosis the agent really produced.
* Storage locations are either a real tank asset id or a named warehouse; a
  warehouse is deliberately *not* dressed up as plant equipment.
* Every finished product sits in a real product-storage tank, and every raw
  material in a real crude-storage tank, so "which tank is it in?" is answerable.
* Movements, balances and production roll-forwards are generated from the same
  seeded stream, so the movement ledger and the closing balances agree.

DETERMINISM
-----------
All variation comes from ``random.Random(117)``, so re-seeding produces byte
identical data. A demo that changes every restart cannot be used in a test.
"""

from __future__ import annotations

import random
from datetime import date, timedelta
from typing import Any

from backend.materials.models import (
    CalculationStatus,
    DataStatus,
    EquipmentMaterialRequirement,
    FinancialEvent,
    FinancialEventType,
    InventoryBalance,
    Material,
    MaterialClass,
    MaterialMovement,
    MovementType,
    PeriodType,
    PriceObservation,
    ProductionOutput,
    Provenance,
    Supplier,
    SupplierStatus,
    new_id,
)
from backend.materials.units import ConversionBasis

SEED_SOURCE = "PROJECT117-SYNTHETIC-DEMO"
SEED_LABEL = "SYNTHETIC DEMO"
SEED_NOTE = (
    "Coherent synthetic refinery data generated by Project 117 for demonstration. "
    "Not MRPL data. Not a market price. Not a real supplier."
)

#: Real product-storage tanks from the refinery dataset.
TANK_MS = "e-TK-1121"  # motor spirit
TANK_DIESEL = "e-TK-1122"  # diesel / ATF
TANK_ATF = "e-TK-1123"
#: Real crude-storage tanks.
TANK_CRUDE_LIGHT = "e-TK-1101"
TANK_CRUDE_HEAVY = "e-TK-1102"

WAREHOUSE_A = "WAREHOUSE-A"
WAREHOUSE_B = "WAREHOUSE-B"

#: Synthetic densities, kg/m³ at 15 °C. Recorded in quality attributes so a
#: KL → MT conversion has a basis to use, and so nobody has to guess one.
DENSITY_LIGHT_CRUDE = 845.0
DENSITY_HEAVY_CRUDE = 915.0
DENSITY_NAPHTHA = 700.0
DENSITY_GASOLINE = 745.0
DENSITY_DIESEL = 832.0
DENSITY_ATF = 800.0
DENSITY_LUBE_OIL = 880.0

SUPPLIERS: list[dict[str, Any]] = [
    {
        "id": "SUP-001",
        "name": "Demo Supplier — Rotating Equipment Spares",
        "lead_time_days": 30,
        "status": SupplierStatus.QUALIFIED,
        "contact": "sales@example-supplier-001.invalid",
        "reference": "SYNTHETIC DEMO — not a real vendor",
    },
    {
        "id": "SUP-002",
        "name": "Demo Supplier — Bearings & Transmission",
        "lead_time_days": 21,
        "status": SupplierStatus.ACTIVE,
        "contact": "orders@example-supplier-002.invalid",
        "reference": "SYNTHETIC DEMO — not a real vendor",
    },
    {
        "id": "SUP-003",
        "name": "Demo Supplier — Valves & Actuation",
        "lead_time_days": 45,
        "status": SupplierStatus.ACTIVE,
        "contact": "support@example-supplier-003.invalid",
        "reference": "SYNTHETIC DEMO — not a real vendor",
    },
    {
        "id": "SUP-004",
        "name": "Demo Supplier — Static Equipment & Bundles",
        "lead_time_days": 90,
        "status": SupplierStatus.QUALIFIED,
        "contact": "projects@example-supplier-004.invalid",
        "reference": "SYNTHETIC DEMO — not a real vendor",
    },
    {
        "id": "SUP-005",
        "name": "Demo Supplier — Catalyst & Chemicals",
        "lead_time_days": 60,
        "status": SupplierStatus.ON_HOLD,
        "contact": "catalyst@example-supplier-005.invalid",
        "reference": "SYNTHETIC DEMO — not a real vendor",
    },
    {
        "id": "SUP-006",
        "name": "Demo Supplier — Crude & Feedstock (trading desk)",
        "lead_time_days": 12,
        "status": SupplierStatus.ACTIVE,
        "contact": "desk@example-supplier-006.invalid",
        "reference": "SYNTHETIC DEMO — not a real vendor",
    },
]

# --------------------------------------------------------------------- materials

RAW_MATERIALS: list[dict[str, Any]] = [
    {
        "id": "RM-CRUDE-LIGHT",
        "name": "Light crude feedstock",
        "unit": "MT",
        "location": TANK_CRUDE_LIGHT,
        "description": "Low-sulphur crude charged to the crude distillation unit.",
        "quality": {
            "density_kg_per_m3": DENSITY_LIGHT_CRUDE,
            "sulphur_pct": 0.42,
            "api_gravity": 35.4,
        },
        "supplier_id": "SUP-006",
        "cost_basis": "landed cost, ex-tax, per MT",
    },
    {
        "id": "RM-CRUDE-HEAVY",
        "name": "Heavy crude feedstock",
        "unit": "MT",
        "location": TANK_CRUDE_HEAVY,
        "description": "Higher-density crude blended into the charge for margin.",
        "quality": {
            "density_kg_per_m3": DENSITY_HEAVY_CRUDE,
            "sulphur_pct": 2.10,
            "api_gravity": 22.8,
        },
        "supplier_id": "SUP-006",
        "cost_basis": "landed cost, ex-tax, per MT",
    },
]

#: Streams exist between two real process areas, never in a tank.
INTERMEDIATES: list[dict[str, Any]] = [
    {
        "id": "INT-DESALTED-CRUDE",
        "name": "Desalted crude",
        "unit": "MT",
        "from_area": "desalter",
        "to_area": "cdu",
        "description": "Crude after desalting, charged to the atmospheric column.",
        "quality": {"density_kg_per_m3": DENSITY_LIGHT_CRUDE, "salt_ptb": 2.1},
    },
    {
        "id": "INT-ATMOS-RESID",
        "name": "Atmospheric residue",
        "unit": "MT",
        "from_area": "cdu",
        "to_area": "vdu",
        "description": "Bottoms from the atmospheric column, routed to vacuum distillation.",
        "quality": {"density_kg_per_m3": 960.0},
    },
    {
        "id": "INT-VGO",
        "name": "Vacuum gas oil",
        "unit": "MT",
        "from_area": "vdu",
        "to_area": "fcc",
        "description": "VGO feed to the fluid catalytic cracker.",
        "quality": {"density_kg_per_m3": 905.0, "sulphur_pct": 1.35},
    },
    {
        "id": "INT-NAPHTHA",
        "name": "Heavy naphtha",
        "unit": "MT",
        "from_area": "cdu",
        "to_area": "nht",
        "description": "Naphtha cut routed to naphtha hydrotreating.",
        "quality": {"density_kg_per_m3": DENSITY_NAPHTHA, "sulphur_pct": 0.09},
    },
    {
        "id": "INT-REFORMATE",
        "name": "Reformate",
        "unit": "MT",
        "from_area": "reformer",
        "to_area": "product-storage",
        "description": "High-octane reformate to the gasoline pool.",
        "quality": {"density_kg_per_m3": DENSITY_GASOLINE, "ron": 98.5},
    },
    {
        "id": "INT-FCC-GASOLINE",
        "name": "FCC gasoline",
        "unit": "MT",
        "from_area": "fcc",
        "to_area": "product-storage",
        "description": "Cracked gasoline to blending.",
        "quality": {"density_kg_per_m3": DENSITY_GASOLINE, "ron": 92.0},
    },
    {
        "id": "INT-DHT-DIESEL",
        "name": "Hydrotreated diesel",
        "unit": "MT",
        "from_area": "dht",
        "to_area": "product-storage",
        "description": "Diesel after hydrotreating, to the diesel pool.",
        "quality": {"density_kg_per_m3": DENSITY_DIESEL, "sulphur_ppm": 42.0},
    },
    {
        "id": "INT-SULFUR",
        "name": "Recovered sulphur",
        "unit": "MT",
        "from_area": "sulfur",
        "to_area": "product-storage",
        "description": "Elemental sulphur recovered from acid gas.",
        "quality": {"purity_pct": 99.8},
    },
]

FINISHED_PRODUCTS: list[dict[str, Any]] = [
    {
        "id": "FP-MOTOR-SPIRIT",
        "name": "Motor spirit (gasoline)",
        "unit": "MT",
        "location": TANK_MS,
        "description": "Finished gasoline to dispatch.",
        "quality": {"density_kg_per_m3": DENSITY_GASOLINE, "ron": 95.0, "sulphur_ppm": 8.0},
    },
    {
        "id": "FP-DIESEL",
        "name": "Diesel (HSD)",
        "unit": "MT",
        "location": TANK_DIESEL,
        "description": "Finished high-speed diesel to dispatch.",
        "quality": {"density_kg_per_m3": DENSITY_DIESEL, "sulphur_ppm": 42.0, "cetane": 51.0},
    },
    {
        "id": "FP-ATF",
        "name": "Aviation turbine fuel",
        "unit": "MT",
        "location": TANK_ATF,
        "description": "Finished ATF to dispatch.",
        "quality": {"density_kg_per_m3": DENSITY_ATF, "freeze_point_c": -47.0},
    },
]

#: ``equipment_id`` and ``failure_mode`` are both from the real dataset.
SPARES: list[dict[str, Any]] = [
    {
        "id": "MECH-SEAL-P1001",
        "name": "Mechanical seal kit — crude charge pump",
        "unit": "EA",
        "location": WAREHOUSE_A,
        "supplier_id": "SUP-001",
        "equipment_id": "e-P-1001",
        "failure_mode": "seal_leak",
        "purpose": "Seal replacement on seal-leak diagnosis",
        "schedule": "on condition",
        "quality": {"material": "SiC/SiC", "shaft_size_mm": 65},
    },
    {
        "id": "MECH-SEAL-P1002",
        "name": "Mechanical seal kit — crude charge pump B",
        "unit": "EA",
        "location": WAREHOUSE_A,
        "supplier_id": "SUP-001",
        "equipment_id": "e-P-1002",
        "failure_mode": "seal_leak",
        "purpose": "Seal replacement on seal-leak diagnosis",
        "schedule": "on condition",
        "quality": {"material": "SiC/SiC", "shaft_size_mm": 65},
    },
    {
        "id": "BEARING-P1042",
        "name": "Thrust bearing set — CDU bottoms pump",
        "unit": "EA",
        "location": WAREHOUSE_A,
        "supplier_id": "SUP-002",
        "equipment_id": "e-P-1042",
        "failure_mode": "bearing_wear",
        "purpose": "Bearing replacement on wear trend",
        "schedule": "planned",
        "quality": {"type": "angular contact", "bore_mm": 90},
    },
    {
        "id": "BEARING-C1053",
        "name": "Compressor bearing set — VDU overhead",
        "unit": "EA",
        "location": WAREHOUSE_B,
        "supplier_id": "SUP-002",
        "equipment_id": "e-C-1053",
        "failure_mode": "bearing_overheat",
        "purpose": "Bearing replacement on overheat trip",
        "schedule": "planned",
        "quality": {"type": "journal", "bore_mm": 120},
    },
    {
        "id": "IMPELLER-P1051",
        "name": "Impeller — VDU feed pump",
        "unit": "EA",
        "location": WAREHOUSE_B,
        "supplier_id": "SUP-001",
        "equipment_id": "e-P-1051",
        "failure_mode": "cavitation",
        "purpose": "Impeller replacement after cavitation damage",
        "schedule": "on condition",
        "quality": {"material": "CA6NM", "diameter_mm": 340},
    },
    {
        "id": "GASKET-V1003",
        "name": "Body gasket set — crude inlet valve",
        "unit": "EA",
        "location": WAREHOUSE_A,
        "supplier_id": "SUP-003",
        "equipment_id": "e-V-1003",
        "failure_mode": "valve_stuck",
        "purpose": "Valve overhaul gasket set",
        "schedule": "planned",
        "quality": {"material": "spiral wound SS316/graphite"},
    },
    {
        "id": "ACTUATOR-V1047",
        "name": "Pneumatic actuator — CDU control valve",
        "unit": "EA",
        "location": WAREHOUSE_B,
        "supplier_id": "SUP-003",
        "equipment_id": "e-V-1047",
        "failure_mode": "valve_stuck",
        "purpose": "Actuator replacement on stuck valve",
        "schedule": "on condition",
        "quality": {"stroke_mm": 100, "action": "air-to-open"},
    },
    {
        "id": "TUBEBUNDLE-E1004",
        "name": "Tube bundle — crude preheat exchanger",
        "unit": "EA",
        "location": WAREHOUSE_B,
        "supplier_id": "SUP-004",
        "equipment_id": "e-E-1004",
        "failure_mode": None,
        "purpose": "Bundle replacement at turnaround",
        "schedule": "turnaround",
        "quality": {"tubes": 420, "material": "CS"},
    },
    {
        "id": "FILTER-C1112",
        "name": "Filter cartridge set — hydrogen compressor",
        "unit": "EA",
        "location": WAREHOUSE_A,
        "supplier_id": "SUP-001",
        "equipment_id": "e-C-1112",
        "failure_mode": None,
        "purpose": "Routine inlet filtration change-out",
        "schedule": "recurring 90 days",
        "quality": {"micron": 10, "per_set": 4},
    },
    {
        "id": "VALVETRIM-V1103",
        "name": "Valve trim set — crude storage isolation",
        "unit": "EA",
        "location": WAREHOUSE_A,
        "supplier_id": "SUP-003",
        "equipment_id": "e-V-1103",
        "failure_mode": "valve_stuck",
        "purpose": "Trim replacement on isolation valve overhaul",
        "schedule": "planned",
        "quality": {"size_in": 12, "rating": "300#"},
    },
    {
        "id": "LUBE-OIL-ISO46",
        "name": "Turbine lube oil ISO VG46",
        "unit": "KL",
        "location": WAREHOUSE_A,
        "supplier_id": "SUP-005",
        "equipment_id": "e-C-1053",
        "failure_mode": "bearing_overheat",
        "purpose": "Oil top-up and change-out on the compressor train",
        "schedule": "recurring 180 days",
        "quality": {"density_kg_per_m3": DENSITY_LUBE_OIL, "iso_grade": "VG46"},
    },
    {
        "id": "CATALYST-FCC",
        "name": "FCC equilibrium catalyst make-up",
        "unit": "MT",
        "location": WAREHOUSE_B,
        "supplier_id": "SUP-005",
        "equipment_id": "e-VS-1081",
        "failure_mode": None,
        "purpose": "Daily catalyst make-up to hold activity",
        "schedule": "recurring 30 days",
        "quality": {"density_kg_per_m3": 900.0, "activity_pct": 68.0},
    },
]

#: Opening balances: quantity / reserved / safety stock / reorder level.
#: Chosen so the demo exercises every threshold state — one healthy spare, one
#: below safety stock, one out of stock, one depleting feedstock.
BALANCES: dict[str, dict[str, float]] = {
    "RM-CRUDE-LIGHT": {
        "quantity": 46_800.0,
        "reserved": 4_200.0,
        "safety": 12_000.0,
        "reorder": 20_000.0,
    },
    "RM-CRUDE-HEAVY": {
        "quantity": 9_400.0,
        "reserved": 6_100.0,
        "safety": 8_000.0,
        "reorder": 14_000.0,
    },
    "INT-DESALTED-CRUDE": {"quantity": 3_100.0, "reserved": 0.0, "safety": 500.0, "reorder": 900.0},
    "INT-ATMOS-RESID": {"quantity": 2_450.0, "reserved": 0.0, "safety": 400.0, "reorder": 800.0},
    "INT-VGO": {"quantity": 1_820.0, "reserved": 260.0, "safety": 300.0, "reorder": 600.0},
    "INT-NAPHTHA": {"quantity": 1_240.0, "reserved": 0.0, "safety": 200.0, "reorder": 400.0},
    "INT-REFORMATE": {"quantity": 940.0, "reserved": 120.0, "safety": 150.0, "reorder": 300.0},
    "INT-FCC-GASOLINE": {"quantity": 1_360.0, "reserved": 180.0, "safety": 200.0, "reorder": 400.0},
    "INT-DHT-DIESEL": {"quantity": 2_080.0, "reserved": 240.0, "safety": 300.0, "reorder": 600.0},
    "INT-SULFUR": {"quantity": 320.0, "reserved": 40.0, "safety": 50.0, "reorder": 100.0},
    "FP-MOTOR-SPIRIT": {
        "quantity": 18_600.0,
        "reserved": 3_400.0,
        "safety": 6_000.0,
        "reorder": 9_000.0,
    },
    "FP-DIESEL": {
        "quantity": 24_200.0,
        "reserved": 5_100.0,
        "safety": 7_000.0,
        "reorder": 11_000.0,
    },
    "FP-ATF": {"quantity": 5_200.0, "reserved": 900.0, "safety": 3_000.0, "reorder": 5_000.0},
    "MECH-SEAL-P1001": {"quantity": 18.0, "reserved": 3.0, "safety": 5.0, "reorder": 8.0},
    "MECH-SEAL-P1002": {"quantity": 6.0, "reserved": 2.0, "safety": 5.0, "reorder": 8.0},
    "BEARING-P1042": {"quantity": 4.0, "reserved": 0.0, "safety": 2.0, "reorder": 4.0},
    "BEARING-C1053": {"quantity": 1.0, "reserved": 0.0, "safety": 2.0, "reorder": 3.0},
    "IMPELLER-P1051": {"quantity": 0.0, "reserved": 0.0, "safety": 1.0, "reorder": 2.0},
    "GASKET-V1003": {"quantity": 11.0, "reserved": 1.0, "safety": 3.0, "reorder": 5.0},
    "ACTUATOR-V1047": {"quantity": 2.0, "reserved": 0.0, "safety": 1.0, "reorder": 2.0},
    "TUBEBUNDLE-E1004": {"quantity": 1.0, "reserved": 1.0, "safety": 1.0, "reorder": 1.0},
    "FILTER-C1112": {"quantity": 14.0, "reserved": 2.0, "safety": 4.0, "reorder": 8.0},
    "VALVETRIM-V1103": {"quantity": 3.0, "reserved": 0.0, "safety": 1.0, "reorder": 2.0},
    "LUBE-OIL-ISO46": {"quantity": 6.5, "reserved": 1.0, "safety": 2.0, "reorder": 4.0},
    "CATALYST-FCC": {"quantity": 96.0, "reserved": 24.0, "safety": 30.0, "reorder": 60.0},
}

#: Base unit prices in the material's own unit. Synthetic, not market quotes.
BASE_PRICES: dict[str, float] = {
    "RM-CRUDE-LIGHT": 48_200.0,
    "RM-CRUDE-HEAVY": 42_600.0,
    "INT-DESALTED-CRUDE": 48_600.0,
    "INT-ATMOS-RESID": 31_400.0,
    "INT-VGO": 44_100.0,
    "INT-NAPHTHA": 55_800.0,
    "INT-REFORMATE": 79_400.0,
    "INT-FCC-GASOLINE": 74_900.0,
    "INT-DHT-DIESEL": 71_200.0,
    "INT-SULFUR": 12_800.0,
    "FP-MOTOR-SPIRIT": 81_600.0,
    "FP-DIESEL": 73_400.0,
    "FP-ATF": 86_900.0,
    "MECH-SEAL-P1001": 12_500.0,
    "MECH-SEAL-P1002": 12_500.0,
    "BEARING-P1042": 8_400.0,
    "BEARING-C1053": 15_700.0,
    "IMPELLER-P1051": 46_300.0,
    "GASKET-V1003": 2_950.0,
    "ACTUATOR-V1047": 38_200.0,
    "TUBEBUNDLE-E1004": 285_000.0,
    "FILTER-C1112": 3_150.0,
    "VALVETRIM-V1103": 21_400.0,
    "LUBE-OIL-ISO46": 96_000.0,
    "CATALYST-FCC": 214_000.0,
}

#: Daily production baseline, MT/day, per finished product, with the process unit
#: that makes it. Real unit asset ids where one exists.
PRODUCTION_BASE: dict[str, tuple[float, str]] = {
    "FP-MOTOR-SPIRIT": (620.0, "e-COL-1044"),
    "FP-DIESEL": (880.0, "e-COL-1052"),
    "FP-ATF": (180.0, "e-COL-1044"),
}


def _prov(note: str = "") -> Provenance:
    return Provenance(
        source=SEED_SOURCE,
        data_status=DataStatus.SYNTHETIC_DEMO,
        note=note or SEED_NOTE,
    )


def _density_basis(material_id: str, density: float) -> ConversionBasis:
    return ConversionBasis(
        kg_per_m3=density,
        source=f"{SEED_SOURCE}: recorded density for {material_id}",
        note="Synthetic density, 15 °C basis.",
    )


def _material_defs() -> list[tuple[dict[str, Any], MaterialClass]]:
    out: list[tuple[dict[str, Any], MaterialClass]] = []
    out += [(m, MaterialClass.RAW_MATERIAL) for m in RAW_MATERIALS]
    out += [(m, MaterialClass.INTERMEDIATE) for m in INTERMEDIATES]
    out += [(m, MaterialClass.FINISHED_PRODUCT) for m in FINISHED_PRODUCTS]
    out += [(m, MaterialClass.MAINTENANCE_SPARE) for m in SPARES]
    return out


def seed_materials(
    store: Any,
    *,
    today: date | None = None,
    price_days: int = 365,
    production_days: int = 180,
) -> dict[str, Any]:
    """Populate an empty :class:`MaterialsStore` with coherent demo data.

    Refuses to run against a non-empty store unless the caller has cleared it
    first, so seeding twice cannot silently double every quantity.
    """
    if not store.is_empty():
        raise RuntimeError(
            "materials store already contains data; call clear() first if a re-seed is intended"
        )

    anchor = today or date.today()
    rng = random.Random(117)

    suppliers = [_supplier(s) for s in SUPPLIERS]
    for s in suppliers:
        store.upsert_supplier(s)

    materials: list[dict[str, Any]] = []
    density_by_id: dict[str, float | None] = {}
    for spec, klass in _material_defs():
        density = spec.get("quality", {}).get("density_kg_per_m3")
        density_by_id[spec["id"]] = density
        material = Material(
            id=spec["id"],
            name=spec["name"],
            material_class=klass,
            unit=spec["unit"],
            location=spec.get("location", ""),
            status=_opening_status(spec["id"]),
            description=spec.get("description", ""),
            quality_attributes=dict(spec.get("quality", {})),
            supplier_id=spec.get("supplier_id"),
            cost_basis=spec.get("cost_basis", "synthetic demo cost basis"),
            source_process_unit=spec.get("from_area"),
            destination_process_unit=spec.get("to_area"),
            provenance=_prov(f"{SEED_NOTE} Class: {klass.value}."),
        )
        materials.append(store.upsert_material(material))

    balances = _seed_balances(store, anchor)
    movements = _seed_movements(store, rng, anchor, density_by_id)
    prices = _seed_prices(store, rng, anchor, days=price_days)
    production = _seed_production(store, rng, anchor, days=production_days)
    requirements = _seed_requirements(store)
    financial = _seed_financial(store, anchor, production)

    return {
        "source": SEED_SOURCE,
        "label": SEED_LABEL,
        "note": SEED_NOTE,
        "materials": len(materials),
        "suppliers": len(suppliers),
        "balances": balances,
        "movements": movements,
        "price_observations": prices,
        "production_records": production,
        "equipment_requirements": requirements,
        "financial_events": financial,
        "counts": store.counts(),
    }


def _supplier(spec: dict[str, Any]) -> Supplier:
    return Supplier(
        id=spec["id"],
        name=spec["name"],
        lead_time_days=int(spec["lead_time_days"]),
        status=spec["status"],
        contact=spec.get("contact", ""),
        reference=spec.get("reference", ""),
        provenance=_prov(),
    )


def _opening_status(material_id: str) -> str:
    """Status implied by the opening balance, so material and balance agree."""
    b = BALANCES.get(material_id)
    if not b:
        return "NORMAL"
    available = b["quantity"] - b["reserved"]
    if available <= 0:
        return "OUT_OF_STOCK"
    if available <= b["safety"]:
        return "CRITICAL"
    if available <= b["reorder"]:
        return "DEPLETING"
    return "AVAILABLE"


def _seed_balances(store: Any, anchor: date) -> int:
    written = 0
    for spec, klass in _material_defs():
        spec_id = spec["id"]
        b = BALANCES.get(spec_id)
        if not b:
            continue
        location = spec.get("location") or spec.get("to_area") or "UNALLOCATED"
        balance = InventoryBalance(
            id=new_id("BAL"),
            material_id=spec_id,
            location=location,
            quantity=b["quantity"],
            reserved=b["reserved"],
            unit=spec["unit"],
            threshold=b["reorder"],
            safety_stock=b["safety"],
            reorder_level=b["reorder"],
            timestamp=f"{anchor.isoformat()}T06:00:00+00:00",
            provenance=_prov(f"{SEED_NOTE} Opening balance."),
        )
        store.add_balance(balance)
        written += 1
    return written


def _seed_movements(
    store: Any,
    rng: random.Random,
    anchor: date,
    density_by_id: dict[str, float | None],
) -> int:
    """90 days of receipts, consumption, production and dispatches.

    Quantities are generated once per material and then applied to a running
    total, so the ledger and the opening balance stay consistent by construction
    rather than by hope.
    """
    written = 0
    for spec, klass in _material_defs():
        mid = spec["id"]
        unit = spec["unit"]
        location = spec.get("location") or spec.get("to_area") or "UNALLOCATED"
        events = 10 if klass is not MaterialClass.MAINTENANCE_SPARE else 5
        for i in range(events):
            days_ago = rng.randint(1, 90)
            when = f"{(anchor - timedelta(days=days_ago)).isoformat()}T0{rng.randint(1, 9)}:00:00+00:00"
            if klass is MaterialClass.RAW_MATERIAL:
                movement_type = MovementType.RECEIPT if i % 2 == 0 else MovementType.CONSUMPTION
                qty = round(rng.uniform(1_500, 9_000), 1)
                src, dst = "SUPPLIER-LOADING", location
            elif klass is MaterialClass.INTERMEDIATE:
                movement_type = MovementType.PRODUCTION
                qty = round(rng.uniform(80, 600), 1)
                src, dst = spec.get("from_area", ""), spec.get("to_area", "")
            elif klass is MaterialClass.FINISHED_PRODUCT:
                movement_type = MovementType.DISPATCH if i % 3 else MovementType.PRODUCTION
                qty = round(rng.uniform(200, 1_800), 1)
                src, dst = location, "DISPATCH-GANTRY"
            else:
                movement_type = MovementType.CONSUMPTION
                qty = float(rng.randint(1, 4))
                src, dst = location, spec.get("equipment_id", "")
            store.append_movement(
                MaterialMovement(
                    id=new_id("MV"),
                    material_id=mid,
                    movement_type=movement_type,
                    quantity=qty,
                    unit=unit,
                    timestamp=when,
                    source_location=src or "",
                    destination_location=dst or "",
                    reference=f"SYNTH-DOC-{rng.randint(10000, 99999)}",
                    provenance=_prov(f"{SEED_NOTE} Movement type: {movement_type.value}."),
                )
            )
            written += 1
    return written


def _seed_prices(store: Any, rng: random.Random, anchor: date, *, days: int) -> int:
    """Append-only price history.

    Fluid commodities get a daily observation; discrete spares get one every
    third day, which is realistic (a spare is not repriced daily) and keeps the
    7D/30D/90D/1Y windows populated for every item.

    One row is deliberately written as ``MANUAL`` — an operator-entered figure —
    so the status distinction is visible in the UI rather than merely supported.
    """
    written = 0
    for spec, klass in _material_defs():
        mid = spec["id"]
        base = BASE_PRICES.get(mid)
        if base is None:
            continue
        unit = spec["unit"]
        step = 1 if klass in (MaterialClass.RAW_MATERIAL, MaterialClass.FINISHED_PRODUCT) else 3
        # A slow drift plus noise, seeded, so the trend is stable across restarts.
        drift = rng.uniform(-0.00035, 0.00055)
        walk = 0.0
        series: list[tuple[date, float]] = []
        for back in range(days, -1, -step):
            day = anchor - timedelta(days=back)
            walk = walk * 0.94 + rng.gauss(0, 0.006)
            factor = 1.0 + drift * (days - back) + walk
            series.append((day, max(base * 0.55, base * factor)))
        for idx, (day, price) in enumerate(series):
            status = DataStatus.SYNTHETIC_DEMO
            note = SEED_NOTE
            source = SEED_SOURCE
            if idx == len(series) // 2 and klass is MaterialClass.MAINTENANCE_SPARE:
                status = DataStatus.MANUAL
                source = "OPERATOR-ENTRY"
                note = f"{SEED_NOTE} Entered by hand for demonstration."
            store.append_price(
                PriceObservation(
                    id=new_id("PRC"),
                    item_id=mid,
                    price=round(price, 2),
                    currency="INR",
                    unit=unit,
                    observed_on=day.isoformat(),
                    source=source,
                    data_status=status,
                    note=note,
                    provenance=Provenance(
                        source=source,
                        data_status=status,
                        timestamp=f"{day.isoformat()}T00:00:00+00:00",
                        note=note,
                    ),
                )
            )
            written += 1
    return written


def _seed_production(store: Any, rng: random.Random, anchor: date, *, days: int) -> int:
    """Daily output with a reconciling roll-forward per record.

    Only DAILY rows are stored; the weekly and monthly views aggregate them (see
    ``backend.materials.service.production_series``). Storing the same production
    at three granularities would be three chances for them to disagree.
    """
    written = 0
    for product_id, (base, unit_id) in PRODUCTION_BASE.items():
        material = next(m for m in FINISHED_PRODUCTS if m["id"] == product_id)
        opening = BALANCES.get(product_id, {}).get("quantity", 0.0) * 0.15
        for back in range(days, -1, -1):
            day = anchor - timedelta(days=back)
            weekly = 1.0 + 0.09 * (day.weekday() >= 5)
            trend = 1.0 + (days - back) / days * rng.uniform(-0.05, 0.07)
            quantity = round(base * weekly * trend * rng.uniform(0.93, 1.07), 2)
            dispatched = round(quantity * rng.uniform(0.72, 0.95), 2)
            adjustment = round(rng.uniform(-4, 4), 2)
            closing = round(opening + quantity - dispatched + adjustment, 2)
            store.add_production(
                ProductionOutput(
                    id=new_id("PRD"),
                    product_id=product_id,
                    process_unit_id=unit_id,
                    quantity=quantity,
                    unit=material["unit"],
                    period_type=PeriodType.DAILY,
                    period_start=day.isoformat(),
                    period_end=day.isoformat(),
                    source=SEED_SOURCE,
                    opening=round(opening, 2),
                    receipts=quantity,
                    dispatches=dispatched,
                    adjustments=adjustment,
                    closing=closing,
                    provenance=_prov(f"{SEED_NOTE} Daily production, roll-forward reconciled."),
                )
            )
            opening = max(0.0, closing)
            written += 1
    return written


def _seed_requirements(store: Any) -> int:
    """Equipment → material requirements, on real asset ids and real failure modes."""
    written = 0
    for spec in SPARES:
        equipment_id = spec.get("equipment_id")
        if not equipment_id:
            continue
        quantity = 2.0 if spec["unit"] == "EA" else round(BALANCES[spec["id"]]["safety"], 2)
        store.upsert_requirement(
            EquipmentMaterialRequirement(
                id=f"REQ-{spec['id']}",
                equipment_id=equipment_id,
                item_id=spec["id"],
                quantity=quantity,
                unit=spec["unit"],
                schedule=spec.get("schedule", ""),
                purpose=spec.get("purpose", ""),
                failure_mode=spec.get("failure_mode"),
                provenance=_prov(
                    f"{SEED_NOTE} Requirement derived from the asset's own spare definition."
                ),
            )
        )
        written += 1
    return written


def _seed_financial(store: Any, anchor: date, production_written: int) -> int:
    """Financial events derived from real stored quantities and prices.

    Every amount is quantity × unit cost from the same database, and carries
    ``ILLUSTRATIVE`` so nobody reads it as a booked figure.
    """
    written = 0
    for spec, klass in _material_defs():
        mid = spec["id"]
        b = BALANCES.get(mid)
        base = BASE_PRICES.get(mid)
        if not b or base is None:
            continue
        value = round(b["quantity"] * base, 2)
        store.add_financial_event(
            FinancialEvent(
                id=new_id("FIN"),
                event_type=FinancialEventType.INVENTORY_COST,
                amount=value,
                currency="INR",
                occurred_on=anchor.isoformat(),
                reference=mid,
                calculation_status=CalculationStatus.ILLUSTRATIVE,
                basis={
                    "quantity": b["quantity"],
                    "unit": spec["unit"],
                    "unit_cost": base,
                    "formula": "quantity × synthetic unit cost",
                },
                provenance=_prov(f"{SEED_NOTE} Inventory value, illustrative."),
            )
        )
        written += 1
        if klass is MaterialClass.RAW_MATERIAL:
            consumed = round(b["quantity"] * 0.08, 2)
            store.add_financial_event(
                FinancialEvent(
                    id=new_id("FIN"),
                    event_type=FinancialEventType.MATERIAL_COST,
                    amount=round(consumed * base, 2),
                    currency="INR",
                    occurred_on=anchor.isoformat(),
                    reference=mid,
                    calculation_status=CalculationStatus.ILLUSTRATIVE,
                    basis={
                        "consumed": consumed,
                        "unit": spec["unit"],
                        "unit_cost": base,
                        "formula": "consumed × synthetic unit cost",
                    },
                    provenance=_prov(f"{SEED_NOTE} Illustrative feedstock cost."),
                )
            )
            written += 1
    for product_id, (base, _unit_id) in PRODUCTION_BASE.items():
        price = BASE_PRICES.get(product_id)
        if price is None:
            continue
        store.add_financial_event(
            FinancialEvent(
                id=new_id("FIN"),
                event_type=FinancialEventType.PRODUCTION_VALUE,
                amount=round(base * price, 2),
                currency="INR",
                occurred_on=anchor.isoformat(),
                reference=product_id,
                calculation_status=CalculationStatus.ILLUSTRATIVE,
                basis={
                    "daily_output": base,
                    "unit": "MT",
                    "unit_value": price,
                    "formula": "daily output × synthetic product value",
                },
                provenance=_prov(f"{SEED_NOTE} Illustrative production value."),
            )
        )
        written += 1
    return written


__all__ = [
    "BASE_PRICES",
    "BALANCES",
    "SEED_LABEL",
    "SEED_NOTE",
    "SEED_SOURCE",
    "seed_materials",
]
