version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: p117-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - internal_p117

  grafana:
    image: grafana/grafana:11.1.0
    container_name: p117-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - internal_p117
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  internal_p117:
    external: true
