"use client";

/**
 * Equipment QR label — the printed identity of a physical asset.
 *
 * The symbol is the SVG the *backend* rendered (`GET /api/equipment/{id}/qr.svg`,
 * see `backend/api/src/qr_codes.py`). The console deliberately ships no
 * JavaScript QR library: one encoder means the label and the Android scanner can
 * never disagree about the payload, and the payload stays namespaced
 * (`P117:EQUIP:<tag>`) rather than being a public URL.
 *
 * The tag is printed beneath the symbol because a label in a machine room gets
 * scuffed; a human must still be able to read — or type — the code that the
 * damaged square used to carry.
 */
import { useEffect, useState } from "react";
import { Lucide } from "@/components/ui/LucideIcon";
import { consoleData } from "@/lib/data/console";

/** One backend-rendered SVG, inlined so the DOM carries a real `<svg>`. */
export function QrSymbol({
  svg,
  size = 132,
  alt,
  className,
}: {
  svg: string | null;
  size?: number;
  alt: string;
  className?: string;
}) {
  if (!svg) {
    return (
      <div
        className={`cs-qr__missing${className ? ` ${className}` : ""}`}
        style={{ width: size, height: size }}
        role="img"
        aria-label={`QR label for ${alt} is unavailable`}
      >
        QR unavailable
      </div>
    );
  }
  return (
    <div
      className={`cs-qr__svg${className ? ` ${className}` : ""}`}
      style={{ width: size, height: size }}
      role="img"
      aria-label={`QR label for ${alt}`}
      // The string is generated by this project's own backend from the tag it
      // resolved from the dataset — there is no caller-supplied HTML in it.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

/**
 * The asset's QR label plus its printable affordance.
 *
 * `tag` is the real plant tag (`P-1001`); `id` is shown as well so an operator
 * who searched by id can recognise the row. "Print label" opens the printable
 * sheet filtered to this asset — that sheet carries the print stylesheet, so a
 * label is never split across pages and no console chrome reaches the paper.
 */
export function AssetQrLabel({
  id,
  tag,
  name,
  zone,
  size = 132,
}: {
  id: string;
  tag: string;
  name?: string;
  zone?: string;
  size?: number;
}) {
  const [svg, setSvg] = useState<string | null | undefined>(undefined);

  useEffect(() => {
    let alive = true;
    setSvg(undefined);
    consoleData.equipment.qrSvg(id).then((value) => {
      if (alive) setSvg(value);
    });
    return () => {
      alive = false;
    };
  }, [id]);

  return (
    <div className="cs-qr" data-asset-qr={id}>
      {svg === undefined ? (
        <div className="cs-qr__svg cs-qr__svg--pending" style={{ width: size, height: size }} aria-hidden="true" />
      ) : (
        <QrSymbol svg={svg} size={size} alt={tag} />
      )}
      <div className="cs-qr__meta">
        <span className="cs-qr__tag cs-mono">{tag}</span>
        <span className="cs-qr__id cs-mono cs-dim">{id}</span>
        {name && <span className="cs-qr__name">{name}</span>}
        {zone && <span className="cs-qr__zone cs-dim">{zone}</span>}
        <a
          className="cs-btn cs-btn--ghost cs-qr__print"
          href={`/console/equipment/labels?asset=${encodeURIComponent(tag)}`}
          target="_blank"
          rel="noreferrer"
          title={`Open the printable label sheet for ${tag}`}
        >
          <Lucide name="printer" size={13} /> Print label
        </a>
      </div>
    </div>
  );
}
